### ISSUE TITLE
Error Help Please

### ISSUE THREAD

**Issue by KingKoopa08** [andrewshilliday/garage-door-controller#20]
After the application just running no opening garage door or closing etc. I get the below error. Would anyone have any suggestions?

Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(_call.args, *_call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 218, in **call**
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(_args, *_kw)
  File "controller.py", line 112, in status_check
    self.send_opendoor_message(int(time.time() - self.open_time))
  File "controller.py", line 121, in send_opendoor_message
    server = smtplib.SMTP(config["smtphost"], config["smtpport"])
  File "/usr/lib/python2.7/smtplib.py", line 256, in **init**
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

**Comment by andrewshilliday** [comment]
I suspect that this has to do with the error others have reported (that the openhab setting was set to true when it shouldn't have been).  Can you update your code and try again?
