### ISSUE TITLE
http://<url>:8081/st produces an error

### ISSUE THREAD

**Issue by Michael-W** [andrewshilliday/garage-door-controller#92]
pi@hassbian:~/garage-door-controller $ python controller.py
`Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1752, in lineReceived
    self.allContentReceived()
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1845, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 766, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 190, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 241, in render
    body = resrc.render(self)
  File "controller.py", line 302, in render
    door = request.args['id'][0]
exceptions.KeyError: 'id'`

Everything else works very well.  Thank you.

**Comment by Michael-W** [comment]
My understanding is growing.  I thought that the http://<url>:8081/xxx were to return info for another program.  Bad thought!
I love the program for its possibilities and for the education.  Thank you.
